---
- name: Deploy to Tomcat
  hosts: localhost
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        # Pura lamba path mita kar sirf relative path likhein
        src: "target/2023MavenWebAppPipelineWithAnsible.war"
        dest: "/opt/tomcat/webapps/2023MavenWebAppPipelineWithAnsible.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat10
        state: restarted
